[monitoring]
health_check_interval = 5
metrics_collection_interval = 1

[monitoring.alert_thresholds]
cpu_usage = 90.0
memory_usage = 90.0
network_usage = 1000000.0
disk_usage = 1000000.0
latency_ms = 1000.0

[telegram]
bot_token = "YOUR_BOT_TOKEN"
chat_id = "YOUR_CHAT_ID"

[strategy]
rsi_period = 14
rsi_overbought = 70.0
rsi_oversold = 30.0
macd_fast = 12
macd_slow = 26
macd_signal = 9
bb_period = 20
bb_std_dev = 2.0
stoch_k = 14
stoch_d = 3
stoch_smooth = 3
atr_period = 14
ichimoku_tenkan = 9
ichimoku_kijun = 26
ichimoku_senkou_span_b = 52

[market_data]
update_interval = 1
data_source = "binance"
symbol = "BONKUSDT"

[trading]
min_order_size = 10.0
max_order_size = 1000.0
max_open_positions = 3
risk_per_trade = 0.02
max_drawdown = 0.1
max_position_size = 1000.0
max_risk_per_trade = 0.02
max_daily_loss = 0.05
stop_loss_percentage = 0.02
risk_reward_ratio = 2.0
trading_pairs = ["BTC/USD", "ETH/USD"]
risk_level = 0.5
take_profit = 0.10

[api]
coingecko_api_key = ""
coinmarketcap_api_key = ""
update_interval = 60

[logging]
level = "info"
file_path = "logs/trading-bot.log"

[database]
path = "data/trading-bot.db" 