paper_trading = true

[general]
log_level = "info"
data_dir = "data"
backup_dir = "backups"

[api]
# host = "127.0.0.1" # These seem to belong elsewhere or are old?
# port = 8080      # These seem to belong elsewhere or are old?
 ml_api_base_url = "http://localhost:8000"

[database]
# path = "/var/lib/trading-bot/data/trading.db" # Remove path if url is used
# url and max_connections seem missing based on src/config/mod.rs definition
url = "sqlite://data/trading.db" # Changed to use local data dir
max_connections = 10 # Example value

[monitoring]
# alert_threshold = 0.1 # Old/Different structure?
# check_interval = 60   # Old/Different structure?
# Need fields matching MonitoringConfig struct: enable_prometheus, prometheus_port, alert_thresholds = { price_change_threshold, volume_threshold, error_rate_threshold }
enable_prometheus = false
prometheus_port = 9090

[monitoring.alert_thresholds]
price_change_threshold = 0.05
volume_threshold = 10000.0
error_rate_threshold = 0.1

[security]
api_key_rotation_days = 30
# rate_limit_requests = 100 # Missing based on src/config/mod.rs definition
# rate_limit_window_seconds = 60 # Missing based on src/config/mod.rs definition
keychain_service_name = "trading-bot-solana" # Default service name for OS keychain
solana_key_username = "main-solana-key"      # Default username for OS keychain
ton_key_username = "main-ton-key" # Placeholder if TON needed

[dex_trading]
trading_pair_symbol = "SOL/USDC" # Placeholder - Update required
base_token_mint = "So11111111111111111111111111111111111111112" # Placeholder (SOL) - Update required
quote_token_mint = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" # Placeholder (USDC) - Update required
base_token_decimals = 9 # Placeholder (SOL) - Update required
quote_token_decimals = 6 # Placeholder (USDC) - Update required
slippage_bps = 50 # Example: 0.5% slippage 

# Adding placeholders for other missing root config sections/fields based on src/config/mod.rs

[trading]
risk_level = 0.5
max_position_size = 1000.0
stop_loss_percentage = 0.02
take_profit_percentage = 0.1
trading_pairs = ["SOL/USDC"]
paper_trading = true

[telegram]
bot_token = "8181890288:AAGqmSPEMhA8jUfBWkfTyAJV5RkS319Qae8"
chat_id = "5870014144"
enable_notifications = true

[ml]
# Direct fields of MLConfig
loss_function = "CrossEntropy"
learning_rate = 0.001
model_path = "models/trading_model.pt"
scaler_path = "models/scaler.pkl"
python_script_path = "scripts/ml_inference.py"
window_size = 60 # Example: Use last 60 data points (e.g., 1 hour if 1-min data)
min_data_points = 26 # Minimum history needed for preprocessor (e.g., for MACD). Must be >= 26
training_batch_size = 64
training_epochs = 100
early_stopping_patience = 10
save_best_model = true
validation_split = 0.15 # Use 15% of data for validation
evaluation_window_size = 120 # Example: Evaluate performance over last 120 predictions

# Nested Model architecture configuration
[ml.architecture]
input_size = 11 # Number of input features from preprocessor
hidden_size = 64
output_size = 2 # Buy/Sell probabilities
num_layers = 3
dropout = 0.1
activation = "ReLU"

[solana]
rpc_url = "https://api.mainnet-beta.solana.com" # Example Solana RPC URL

# Add missing [logging] section based on other config file
[logging]
level = "info"
file_path = "logs/trading-bot.log" # Use local path